-- MySQL Script generated by MySQL Workbench
-- Tue Apr 15 22:22:03 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente Pessoa Física`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente Pessoa Física` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente Pessoa Física` (
  `idCliente Pessoa Física` INT NOT NULL,
  `CPF` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Endereço` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente Pessoa Física`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Identificação` VARCHAR(45) NULL,
  `Cliente Pessoa Física_idCliente Pessoa Física` INT NOT NULL,
  PRIMARY KEY (`idCliente`, `Cliente Pessoa Física_idCliente Pessoa Física`),
  INDEX `fk_Cliente_Cliente Pessoa Física1_idx` (`Cliente Pessoa Física_idCliente Pessoa Física` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Cliente Pessoa Física1`
    FOREIGN KEY (`Cliente Pessoa Física_idCliente Pessoa Física`)
    REFERENCES `mydb`.`Cliente Pessoa Física` (`idCliente Pessoa Física`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Venda` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Venda` (
  `idvenda` INT NOT NULL,
  `data_venda` DATE NULL,
  `total` INT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idvenda`, `Cliente_idCliente`),
  INDEX `fk_Pedido_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Item_Venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Item_Venda` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Item_Venda` (
  `iditemvenda` INT NOT NULL,
  `Quantidade` INT NULL,
  `Preco_unit` INT NULL,
  PRIMARY KEY (`iditemvenda`),
  INDEX `fk_Pedido_has_Produto_Pedido1_idx` (`iditemvenda` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_has_Produto_Pedido1`
    FOREIGN KEY (`iditemvenda`)
    REFERENCES `mydb`.`Venda` (`idvenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `idProduto` INT NOT NULL,
  `Categoria` VARCHAR(45) NULL,
  `Descrição` VARCHAR(45) NULL,
  `Valor` VARCHAR(45) NULL,
  `Item_Venda_iditemvenda` INT NOT NULL,
  PRIMARY KEY (`idProduto`, `Item_Venda_iditemvenda`),
  INDEX `fk_Produto_Item_Venda1_idx` (`Item_Venda_iditemvenda` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_Item_Venda1`
    FOREIGN KEY (`Item_Venda_iditemvenda`)
    REFERENCES `mydb`.`Item_Venda` (`iditemvenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Fornecedor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedor` (
  `idFornecedor` INT NOT NULL,
  `Razão Social` VARCHAR(45) NULL,
  `CNPJ` VARCHAR(45) NULL,
  PRIMARY KEY (`idFornecedor`),
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fornece`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Fornece` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Fornece` (
  `Fornecedor_idFornecedor` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  PRIMARY KEY (`Fornecedor_idFornecedor`, `Produto_idProduto`),
  INDEX `fk_Fornecedor_has_Produto_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  INDEX `fk_Fornecedor_has_Produto_Fornecedor_idx` (`Fornecedor_idFornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_Fornecedor_has_Produto_Fornecedor`
    FOREIGN KEY (`Fornecedor_idFornecedor`)
    REFERENCES `mydb`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fornecedor_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pagamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pagamento` (
  `idPagamento` INT NOT NULL,
  `Forma de pagamento` VARCHAR(45) NULL,
  `Status do pagamento` VARCHAR(45) NULL,
  `Venda_idVenda` INT NOT NULL,
  PRIMARY KEY (`idPagamento`, `Venda_idVenda`),
  INDEX `fk_Pagamento_Pedido1_idx` (`Venda_idVenda` ASC) VISIBLE,
  CONSTRAINT `fk_Pagamento_Pedido1`
    FOREIGN KEY (`Venda_idVenda`)
    REFERENCES `mydb`.`Venda` (`idvenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cartão`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cartão` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cartão` (
  `idCartão` INT NOT NULL,
  `Data do pagamento` DATE NULL,
  `Tipo de pagamento (Deb/Créd)` VARCHAR(45) NOT NULL,
  `Dados do cartão` VARCHAR(45) NOT NULL,
  `Valor` VARCHAR(45) NOT NULL,
  `Forma de pagamento (Link ou maquininha)` VARCHAR(45) NULL,
  `Pagamento_idPagamento` INT NOT NULL,
  `Pagamento_Venda_idVenda` INT NOT NULL,
  `Pagamento_Venda_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idCartão`, `Pagamento_idPagamento`, `Pagamento_Venda_idVenda`, `Pagamento_Venda_Cliente_idCliente`),
  UNIQUE INDEX `Tipo de pagamento (Deb/Créd)_UNIQUE` (`Tipo de pagamento (Deb/Créd)` ASC) VISIBLE,
  UNIQUE INDEX `Dados do cartão_UNIQUE` (`Dados do cartão` ASC) VISIBLE,
  UNIQUE INDEX `Valor_UNIQUE` (`Valor` ASC) VISIBLE,
  INDEX `fk_Cartão_Pagamento1_idx` (`Pagamento_idPagamento` ASC, `Pagamento_Venda_idVenda` ASC, `Pagamento_Venda_Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cartão_Pagamento1`
    FOREIGN KEY (`Pagamento_idPagamento` , `Pagamento_Venda_idVenda`)
    REFERENCES `mydb`.`Pagamento` (`idPagamento` , `Venda_idVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pix`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pix` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pix` (
  `idPix` INT NOT NULL,
  `Data do pagamento` DATE NULL,
  `Dados do pagante` VARCHAR(45) NOT NULL,
  `Comprovante de pagamento` VARCHAR(45) NOT NULL,
  `Valor` VARCHAR(45) NOT NULL,
  `Pagamento_idPagamento` INT NOT NULL,
  `Pagamento_Venda_idVenda` INT NOT NULL,
  `Pagamento_Venda_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idPix`, `Pagamento_idPagamento`, `Pagamento_Venda_idVenda`, `Pagamento_Venda_Cliente_idCliente`),
  UNIQUE INDEX `Dados do pagante_UNIQUE` (`Dados do pagante` ASC) VISIBLE,
  UNIQUE INDEX `Comprovante de pagamento_UNIQUE` (`Comprovante de pagamento` ASC) VISIBLE,
  UNIQUE INDEX `Valor_UNIQUE` (`Valor` ASC) VISIBLE,
  INDEX `fk_Pix_Pagamento1_idx` (`Pagamento_idPagamento` ASC, `Pagamento_Venda_idVenda` ASC, `Pagamento_Venda_Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Pix_Pagamento1`
    FOREIGN KEY (`Pagamento_idPagamento` , `Pagamento_Venda_idVenda`)
    REFERENCES `mydb`.`Pagamento` (`idPagamento` , `Venda_idVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Funcionario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `idFuncionario` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `CPF` VARCHAR(45) NULL,
  `Cargo` VARCHAR(45) NULL,
  `Venda_idvenda` INT NOT NULL,
  `Venda_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idFuncionario`, `Venda_idvenda`, `Venda_Cliente_idCliente`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  INDEX `fk_Funcionario_Venda1_idx` (`Venda_idvenda` ASC, `Venda_Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Funcionario_Venda1`
    FOREIGN KEY (`Venda_idvenda` , `Venda_Cliente_idCliente`)
    REFERENCES `mydb`.`Venda` (`idvenda` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
